import requests
import time
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich import box

console = Console()

# Disable SSL warnings
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# ─────────────────────────────────────────────────────────────────────────────
# WAF SIGNATURES
# Each WAF has known headers/cookies it injects into responses
# ─────────────────────────────────────────────────────────────────────────────
WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id", "cf-mitigated"],
        "cookies": ["__cf_bm", "__cflb", "cf_clearance"],
        "body":    ["Attention Required! | Cloudflare", "cloudflare-nginx", "Ray ID"],
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "x-check-cacheable", "x-akamai-request-id"],
        "cookies": ["aka_", "akacd_", "akavpau_"],
        "body":    ["Access Denied | Akamai", "Reference #"],
    },
    "Imperva / Incapsula": {
        "headers": ["x-iinfo", "x-cdn"],
        "cookies": ["incap_ses", "visid_incap", "nlbi_"],
        "body":    ["Incapsula incident ID", "Request unsuccessful. Incapsula"],
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id", "x-amzn-trace-id"],
        "cookies": [],
        "body":    ["AWS WAF", "Request blocked"],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "cookies": [],
        "body":    ["Access Denied - Sucuri Website Firewall", "Sucuri WebSite Firewall"],
    },
    "F5 BIG-IP ASM": {
        "headers": ["x-waf-event-info", "x-cnection"],
        "cookies": ["bigipserver", "BIGipServer", "TS"],
        "body":    ["The requested URL was rejected", "F5 Networks"],
    },
    "Azure Front Door": {
        "headers": ["x-azure-ref", "x-fd-healthprobe", "x-msedge-ref"],
        "cookies": [],
        "body":    ["Microsoft Azure Web Application Firewall"],
    },
    "ModSecurity": {
        "headers": ["x-mod-security", "x-modsecurity"],
        "cookies": [],
        "body":    ["ModSecurity", "This error was generated by Mod_Security", "Not Acceptable!"],
    },
    "Wordfence": {
        "headers": [],
        "cookies": ["wfwaf-authcookie"],
        "body":    ["Wordfence", "Generated by Wordfence", "Your access to this site has been limited"],
    },
    "Barracuda": {
        "headers": ["x-barracuda-connect", "x-barracuda-start-scan"],
        "cookies": ["barra_counter_session"],
        "body":    ["Barracuda Web Application Firewall"],
    },
    "Fortinet FortiWeb": {
        "headers": ["x-requestid"],
        "cookies": ["cookiesession1"],
        "body":    ["FortiWeb", "Application Firewall", "FORTIWAFSID"],
    },
    "Nginx (generic WAF)": {
        "headers": [],
        "cookies": [],
        "body":    ["nginx", "403 Forbidden"],
    },
}

# Payloads designed to trigger WAF responses
# These look like common attack patterns WAFs are trained to block
# We're not actually attacking — just probing WAF behavior
PROBE_PAYLOADS = [
    "?id=1'%20OR%20'1'='1",                          # SQLi
    "?q=<script>alert(1)</script>",                   # XSS
    "?file=../../../etc/passwd",                      # Path traversal
    "?cmd=;ls%20-la",                                 # Command injection
    "?search=UNION%20SELECT%201,2,3--",               # SQLi UNION
]

# Status codes that suggest WAF blocking
BLOCK_CODES = {403, 406, 419, 429, 501, 502, 503}

# WAF bypass hints — educational, for authorized testing only
BYPASS_HINTS = {
    "Cloudflare":          "Try origin IP bypass via historical DNS/crt.sh. Use case variation in payloads.",
    "Akamai":              "Header injection, HTTP/2 desync. Look for origin IP in SSL certs.",
    "Imperva / Incapsula": "Try encoding payloads (double URL encode). Look for origin IP leak.",
    "AWS WAF":             "AWS WAF rules are often misconfigured. Try chunked encoding.",
    "Sucuri":              "Origin IP often findable via Shodan or historical DNS.",
    "F5 BIG-IP ASM":       "Try HPP (HTTP Parameter Pollution) and Unicode encoding.",
    "ModSecurity":         "Rule set varies. Try comment injection and whitespace variants.",
    "Wordfence":           "WordPress plugin — try REST API endpoints which may bypass rules.",
    "Azure Front Door":    "Try direct origin IP if discoverable. Header smuggling.",
    "Barracuda":           "Try multipart form encoding for payload delivery.",
    "Fortinet FortiWeb":   "Try HTTP verb tampering and encoding variations.",
}


class WAFDetector:
    def __init__(self, target: str, verbose: bool = False, active: bool = True):
        self.target  = target
        self.verbose = verbose
        self.active  = active  # whether to send probe payloads (active detection)
        self.base_url = self._make_url(target)

        self.session = requests.Session()
        self.session.headers.update({
            "User-Agent":      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36",
            "Accept":          "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.5",
        })

        self.results = {
            "target":      target,
            "detected":    False,
            "waf":         None,
            "confidence":  "none",
            "evidence":    [],
            "blocked":     False,
            "block_codes": [],
            "bypass_hint": None,
            "all_matches": [],  # all WAFs with any signature match
        }

    def run(self) -> dict:
        console.print(Panel(
            f"[bold cyan]WAF Detection[/bold cyan] → [green]{self.base_url}[/green]\n"
            f"[dim]Passive signature scan + {'active payload probing' if self.active else 'passive only'}[/dim]",
            expand=False
        ))

        # Step 1 — Passive: get baseline response, check signatures
        baseline = self._get_baseline()
        if baseline:
            self._passive_detect(baseline)

        # Step 2 — Active: send probes, check for blocking behavior
        if self.active:
            self._active_detect()

        # Step 3 — Determine confidence and finalize
        self._calculate_confidence()

        self._display()
        return self.results

    # -------------------------------------------------------------------------
    # Baseline Request
    # -------------------------------------------------------------------------
    def _get_baseline(self) -> requests.Response:
        try:
            console.print("  [dim][*] Sending baseline request...[/dim]")
            r = self.session.get(self.base_url, timeout=10, verify=False, allow_redirects=True)
            console.print(f"  [dim][*] Baseline: {r.status_code} ({len(r.content)} bytes)[/dim]\n")
            return r
        except Exception as e:
            console.print(f"  [red][!] Baseline request failed: {e}[/red]")
            return None

    # -------------------------------------------------------------------------
    # Passive Detection — header/cookie/body signatures
    # -------------------------------------------------------------------------
    def _passive_detect(self, r: requests.Response):
        headers_lower = {k.lower(): v.lower() for k, v in r.headers.items()}
        cookies_lower = {k.lower(): v for k, v in r.cookies.items()}
        body_lower    = r.text.lower()

        for waf_name, sigs in WAF_SIGNATURES.items():
            matches = []

            # Header signatures
            for sig in sigs["headers"]:
                if any(sig in h for h in headers_lower) or any(sig in v for v in headers_lower.values()):
                    matches.append(f"header:{sig}")

            # Cookie signatures
            for sig in sigs["cookies"]:
                if any(sig in c for c in cookies_lower):
                    matches.append(f"cookie:{sig}")

            # Body signatures (only on block pages — don't scan full body passively)
            if r.status_code in BLOCK_CODES:
                for sig in sigs["body"]:
                    if sig.lower() in body_lower:
                        matches.append(f"body:{sig}")

            if matches:
                self.results["all_matches"].append({
                    "waf":     waf_name,
                    "matches": matches
                })

                if self.verbose:
                    console.print(f"  [dim yellow][~] {waf_name} signature: {', '.join(matches)}[/dim yellow]")

        # Pick the WAF with the most evidence
        if self.results["all_matches"]:
            best = max(self.results["all_matches"], key=lambda x: len(x["matches"]))
            self.results["waf"]      = best["waf"]
            self.results["evidence"] = best["matches"]
            self.results["detected"] = True

    # -------------------------------------------------------------------------
    # Active Detection — payload probing
    # -------------------------------------------------------------------------
    def _active_detect(self):
        console.print("  [dim][*] Sending probe payloads...[/dim]")

        block_codes_seen = []

        for payload in PROBE_PAYLOADS:
            url = f"{self.base_url}{payload}"
            try:
                r = self.session.get(url, timeout=8, verify=False, allow_redirects=True)

                if r.status_code in BLOCK_CODES:
                    block_codes_seen.append(r.status_code)
                    if self.verbose:
                        console.print(f"  [dim red][!] Probe blocked: {payload[:40]} → {r.status_code}[/dim red]")

                    # Check body of block page for WAF signatures
                    body_lower = r.text.lower()
                    for waf_name, sigs in WAF_SIGNATURES.items():
                        for sig in sigs["body"]:
                            if sig.lower() in body_lower:
                                self.results["detected"] = True
                                self.results["waf"]      = waf_name
                                self.results["evidence"].append(f"block_page:{sig}")

                # Small delay between probes — be respectful
                time.sleep(0.5)

            except Exception:
                pass

        if block_codes_seen:
            self.results["blocked"]     = True
            self.results["block_codes"] = list(set(block_codes_seen))
            if not self.results["detected"]:
                # Blocked but couldn't fingerprint — unknown WAF
                self.results["detected"] = True
                self.results["waf"]      = "Unknown WAF"
                self.results["evidence"].append("payload blocked")

    # -------------------------------------------------------------------------
    # Confidence Scoring
    # -------------------------------------------------------------------------
    def _calculate_confidence(self):
        evidence_count = len(self.results["evidence"])
        blocked        = self.results["blocked"]

        if not self.results["detected"]:
            self.results["confidence"] = "none"
        elif blocked and evidence_count >= 2:
            self.results["confidence"] = "high"
        elif blocked or evidence_count >= 2:
            self.results["confidence"] = "medium"
        else:
            self.results["confidence"] = "low"

        # Add bypass hint if WAF detected
        if self.results["waf"] and self.results["waf"] in BYPASS_HINTS:
            self.results["bypass_hint"] = BYPASS_HINTS[self.results["waf"]]

    # -------------------------------------------------------------------------
    # Display
    # -------------------------------------------------------------------------
    def _display(self):
        waf        = self.results["waf"]
        detected   = self.results["detected"]
        confidence = self.results["confidence"]
        evidence   = self.results["evidence"]

        console.print()

        if not detected:
            console.print("  [bold green][+] No WAF detected[/bold green]")
            console.print("  [dim]    Target may be unprotected — proceed carefully.[/dim]")
            return

        # Confidence color
        conf_color = {"high": "red", "medium": "yellow", "low": "dim yellow"}.get(confidence, "white")

        console.print(f"  [bold red][!!!] WAF DETECTED:[/bold red] [bold white]{waf}[/bold white]")
        console.print(f"  [bold white]Confidence:[/bold white] [{conf_color}]{confidence.upper()}[/{conf_color}]")

        if self.results["blocked"]:
            codes = ', '.join(str(c) for c in self.results["block_codes"])
            console.print(f"  [bold white]Blocked:[/bold white]    [red]Yes (HTTP {codes})[/red]")

        # Evidence table
        if evidence:
            console.print()
            t = Table(box=box.SIMPLE, header_style="bold magenta", show_header=True)
            t.add_column("Type",      style="cyan",  width=12)
            t.add_column("Signature", style="white")

            for e in evidence:
                if ":" in e:
                    etype, esig = e.split(":", 1)
                    t.add_row(etype, esig)
                else:
                    t.add_row("match", e)
            console.print(t)

        # All WAFs with any match (secondary matches)
        if len(self.results["all_matches"]) > 1:
            others = [m["waf"] for m in self.results["all_matches"] if m["waf"] != waf]
            if others:
                console.print(f"  [dim]Other partial matches: {', '.join(others)}[/dim]")

        # Bypass hint
        if self.results["bypass_hint"]:
            console.print(f"\n  [bold yellow][*] Bypass hint:[/bold yellow]")
            console.print(f"  [dim yellow]    {self.results['bypass_hint']}[/dim yellow]")

    def _make_url(self, target: str) -> str:
        if target.startswith(("http://", "https://")):
            return target
        return f"https://{target}"
